services:

  db:
    image: postgres:16-alpine
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    container_name: sales-analysis-database
    env_file: ./env/postgres.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: pg_isready -d $$POSTGRES_DB -h db -p 5432 -U $$POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: migprogrammer/sales:v1
    container_name: sales-analysis-application
    ports:
      - "80:80"
    env_file: ./env/app.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: curl -v http://app:80/
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgresql_data: {}